spring:
  ai:
    openai.api-key: sk-secret
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root


logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG
    org.springframework.ai: DEBUG
    org.springframework.web.client: INFO
