spring:
  application:
    name: myai
  ai:
    # openai.api-key: sk-secret
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
  docker:
    compose:
      enabled: true
      file: docker/docker-compose.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG
    org.springframework.ai: DEBUG

management:
  observations:
    annotations:
      enabled: true
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
      timeout: 20s
      compression: gzip
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      produce:
        - W3C
